# Generated by Django 5.0.1 on 2024-01-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.TextField(null=True)),
                ('lastName', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phoneNumber', models.PositiveIntegerField(null=True)),
                ('education', models.TextField(null=True)),
                ('skills', models.TextField(null=True)),
                ('experience', models.TextField(null=True)),
                ('profile', models.FileField(null=True, upload_to='uploads')),
            ],
        ),
    ]
