# Generated by Django 5.0.1 on 2024-01-22 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PortFolioApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserForm',
            new_name='UserModel',
        ),
    ]
